baseurl: "/" 
url: "https://ibrakap.github.io/"

# Build settings
markdown: kramdown
theme: jekyll-theme-console
remote_theme: ibrakap/jekyll-theme-console # Using my fork (b2a3e8/jekyll-theme-console)

header_pages:
  - index.md
  - whoami.md
  - about.md
style: dark
